# Generated by Django 5.2.3 on 2025-06-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
